name: 'SOLR Search Pantheon Recipe'
description: 'Enables and configures essential modules and base search view with facets.'
type: 'Site config'

install:
  - search_api
  - facets
  - search_api_solr
  - search_api_pantheon
  - configurable_views_filter_block
  - language
  - search_api_solr_admin

config:
  import:
    search_api: '*'
    search_api_solr: '*'
    language: '*'
